// Command genprecomp generates the fixed-window secp256k1 base-point table.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/binary"
	"fmt"
	"go/format"
	"math/big"
	"os"
)

const (
	baseWindow  = 5
	baseWindows = 52
	tableSize   = 16
)

var (
	fieldPrime = mustBig("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f")
	generator  = affinePoint{
		x: mustBig("79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798"),
		y: mustBig("483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8"),
	}
	montgomeryR = new(big.Int).Mod(new(big.Int).Lsh(big.NewInt(1), 256), fieldPrime)
)

type affinePoint struct {
	x, y     *big.Int
	infinity bool
}

func main() {
	table := buildTable()
	source, err := os.ReadFile("cmd/genprecomp/main.go")
	if err != nil {
		panic(err)
	}
	sourceHash := sha256.Sum256(source)

	var body bytes.Buffer
	fmt.Fprintf(&body, "var generatorAffineTableW5Words = [%d][%d][8]uint64{\n", baseWindows, tableSize)
	for _, window := range table {
		body.WriteString("\t{\n")
		for _, point := range window {
			x := montgomeryWords(point.x)
			y := montgomeryWords(point.y)
			fmt.Fprintf(&body, "\t\t{%#x, %#x, %#x, %#x, %#x, %#x, %#x, %#x},\n",
				x[0], x[1], x[2], x[3], y[0], y[1], y[2], y[3])
		}
		body.WriteString("\t},\n")
	}
	body.WriteString("}\n")
	dataHash := sha256.Sum256(body.Bytes())

	var output bytes.Buffer
	output.WriteString("// Code generated by cmd/genprecomp; DO NOT EDIT.\n")
	fmt.Fprintf(&output, "// Parameters: base-window=%d.\n", baseWindow)
	fmt.Fprintf(&output, "// Generator source SHA-256: %x.\n", sourceHash)
	fmt.Fprintf(&output, "// Table data SHA-256: %x.\n\n", dataHash)
	output.WriteString("package secp256k1\n\n")
	output.Write(body.Bytes())
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("precompute_table_generated.go", formatted, 0o644); err != nil {
		panic(err)
	}
}

func buildTable() [baseWindows][tableSize]affinePoint {
	var table [baseWindows][tableSize]affinePoint
	base := clone(generator)
	for i := range table {
		current := clone(base)
		for j := range table[i] {
			table[i][j] = clone(current)
			current = add(current, base)
		}
		for range baseWindow {
			base = double(base)
		}
	}
	return table
}

func add(p, q affinePoint) affinePoint {
	if p.infinity {
		return clone(q)
	}
	if q.infinity {
		return clone(p)
	}
	if p.x.Cmp(q.x) == 0 {
		if mod(new(big.Int).Add(p.y, q.y)).Sign() == 0 {
			return affinePoint{infinity: true}
		}
		return double(p)
	}
	numerator := new(big.Int).Sub(q.y, p.y)
	denominator := mod(new(big.Int).Sub(q.x, p.x))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x := mod(new(big.Int).Sub(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), p.x), q.x))
	y := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x)), p.y))
	return affinePoint{x: x, y: y}
}

func double(p affinePoint) affinePoint {
	if p.infinity || p.y.Sign() == 0 {
		return affinePoint{infinity: true}
	}
	numerator := new(big.Int).Mul(p.x, p.x)
	numerator.Mul(numerator, big.NewInt(3))
	denominator := mod(new(big.Int).Lsh(new(big.Int).Set(p.y), 1))
	denominator.ModInverse(denominator, fieldPrime)
	lambda := mod(numerator.Mul(numerator, denominator))
	x := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, lambda), new(big.Int).Lsh(new(big.Int).Set(p.x), 1)))
	y := mod(new(big.Int).Sub(new(big.Int).Mul(lambda, new(big.Int).Sub(p.x, x)), p.y))
	return affinePoint{x: x, y: y}
}

func clone(p affinePoint) affinePoint {
	if p.infinity {
		return affinePoint{infinity: true}
	}
	return affinePoint{x: new(big.Int).Set(p.x), y: new(big.Int).Set(p.y)}
}

func mod(value *big.Int) *big.Int {
	value.Mod(value, fieldPrime)
	if value.Sign() < 0 {
		value.Add(value, fieldPrime)
	}
	return value
}

func montgomeryWords(value *big.Int) [4]uint64 {
	montgomery := new(big.Int).Mul(value, montgomeryR)
	montgomery.Mod(montgomery, fieldPrime)
	var encoded [32]byte
	montgomery.FillBytes(encoded[:])
	return [4]uint64{
		binary.BigEndian.Uint64(encoded[24:32]),
		binary.BigEndian.Uint64(encoded[16:24]),
		binary.BigEndian.Uint64(encoded[8:16]),
		binary.BigEndian.Uint64(encoded[0:8]),
	}
}

func mustBig(value string) *big.Int {
	out, ok := new(big.Int).SetString(value, 16)
	if !ok {
		panic("invalid integer")
	}
	return out
}
