// Code generated by internal/secp256k1/addchain/generate.go. DO NOT EDIT.

package field

// Inv computes z = 1/x mod p. For x = 0, Inv returns 0.
func (z *Element) Inv(x *Element) *Element {
	out := fieldInv(*x)
	return z.Set(&out)
}

func fieldInv(x Element) Element {
	// Addition chain:
	//
	//	_10     = 2*1
	//	_100    = 2*_10
	//	_101    = 1 + _100
	//	_111    = _10 + _101
	//	_1110   = 2*_111
	//	_111000 = _1110 << 2
	//	_111111 = _111 + _111000
	//	i13     = _111111 << 4 + _1110
	//	x12     = i13 << 2 + _111
	//	x22     = x12 << 10 + i13 + 1
	//	i29     = 2*x22
	//	i31     = i29 << 2
	//	i54     = i31 << 22 + i31
	//	i122    = (i54 << 20 + i29) << 46 + i54
	//	x223    = i122 << 110 + i122 + _111
	//	i269    = ((x223 << 23 + x22) << 7 + _101) << 3
	//	return    _101 + i269
	var z Element
	var (
		t0 Element
		t1 Element
		t2 Element
		t3 Element
		t4 Element
	)

	t0.Square(&x)

	z.Square(&t0)

	z.Mul(&x, &z)

	t1.Mul(&t0, &z)

	t0.Square(&t1)
	t2.SquareN(&t0, 2)

	t2.Mul(&t1, &t2)
	t2.SquareN(&t2, 4)

	t0.Mul(&t0, &t2)
	t2.SquareN(&t0, 2)

	t2.Mul(&t1, &t2)
	t2.SquareN(&t2, 10)

	t0.Mul(&t0, &t2)

	t0.Mul(&x, &t0)

	t3.Square(&t0)
	t2.SquareN(&t3, 2)
	t4.SquareN(&t2, 22)

	t2.Mul(&t2, &t4)
	t4.SquareN(&t2, 20)

	t3.Mul(&t3, &t4)
	t3.SquareN(&t3, 46)

	t2.Mul(&t2, &t3)
	t3.SquareN(&t2, 110)

	t2.Mul(&t2, &t3)

	t1.Mul(&t1, &t2)
	t1.SquareN(&t1, 23)

	t0.Mul(&t0, &t1)
	t0.SquareN(&t0, 7)

	t0.Mul(&z, &t0)
	t0.SquareN(&t0, 3)

	z.Mul(&z, &t0)

	return z
}

// sqrtCandidate computes z = x^((p+1)/4) mod p.
func (z *Element) sqrtCandidate(x *Element) *Element {
	out := fieldSqrt(*x)
	return z.Set(&out)
}

func fieldSqrt(x Element) Element {
	// Addition chain:
	//
	//	_10      = 2*1
	//	_11      = 1 + _10
	//	_1100    = _11 << 2
	//	_1111    = _11 + _1100
	//	_11110   = 2*_1111
	//	_11111   = 1 + _11110
	//	_1111100 = _11111 << 2
	//	_1111111 = _11 + _1111100
	//	x11      = _1111111 << 4 + _1111
	//	x22      = x11 << 11 + x11
	//	x27      = x22 << 5 + _11111
	//	x54      = x27 << 27 + x27
	//	x108     = x54 << 54 + x54
	//	x216     = x108 << 108 + x108
	//	x223     = x216 << 7 + _1111111
	//	return     ((x223 << 23 + x22) << 6 + _11) << 2
	var z Element
	var (
		t0 Element
		t1 Element
		t2 Element
		t3 Element
	)

	z.Square(&x)

	z.Mul(&x, &z)
	t0.SquareN(&z, 2)

	t0.Mul(&z, &t0)

	t1.Square(&t0)

	t2.Mul(&x, &t1)
	t1.SquareN(&t2, 2)

	t1.Mul(&z, &t1)
	t3.SquareN(&t1, 4)

	t0.Mul(&t0, &t3)
	t3.SquareN(&t0, 11)

	t0.Mul(&t0, &t3)
	t3.SquareN(&t0, 5)

	t2.Mul(&t2, &t3)
	t3.SquareN(&t2, 27)

	t2.Mul(&t2, &t3)
	t3.SquareN(&t2, 54)

	t2.Mul(&t2, &t3)
	t3.SquareN(&t2, 108)

	t2.Mul(&t2, &t3)
	t2.SquareN(&t2, 7)

	t1.Mul(&t1, &t2)
	t1.SquareN(&t1, 23)

	t0.Mul(&t0, &t1)
	t0.SquareN(&t0, 6)

	z.Mul(&z, &t0)
	z.SquareN(&z, 2)

	return z
}
