// Copyright 2026 The secp256k1 Authors.

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"io"
	"log"
	"os"
	"os/exec"
	"strings"
)

const defaultToolImage = "ghcr.io/islishude/fiat-crypto-go-tool"

type target struct {
	Package  string
	Output   string
	Wrappers []wrapper
}

type wrapper struct {
	Name    string
	Helper  string
	Comment string
	Expr    string
}

var targets = []target{
	{
		Package: "field",
		Output:  "../field/exponent_generated.go",
		Wrappers: []wrapper{
			{
				Name:    "Inv",
				Helper:  "fieldInv",
				Comment: "Inv computes z = 1/x mod p. For x = 0, Inv returns 0.",
				Expr:    "2^256 - 2^32 - 977 - 2",
			},
			{
				Name:    "sqrtCandidate",
				Helper:  "fieldSqrt",
				Comment: "sqrtCandidate computes z = x^((p+1)/4) mod p.",
				Expr:    "2^254 - 2^30 - 244",
			},
		},
	},
}

func main() {
	for _, t := range targets {
		var out bytes.Buffer
		out.WriteString("// Code generated by internal/secp256k1/addchain/generate.go. DO NOT EDIT.\n\n")
		_, _ = out.WriteString("package " + t.Package + "\n\n")
		for _, w := range t.Wrappers {
			_, _ = out.WriteString(generateWrapper(w))
			_ = out.WriteByte('\n')
		}
		formatted, err := format.Source(out.Bytes())
		if err != nil {
			log.Fatalf("format %s: %v\n%s", t.Output, err, out.String())
		}
		if err := os.WriteFile(t.Output, formatted, 0644); err != nil {
			log.Fatal(err)
		}
	}
}

func generateWrapper(w wrapper) string {
	acc := search(w.Expr)
	defer os.Remove(acc)

	tmpl, err := os.CreateTemp(".", "secp256k1-addchain-template")
	if err != nil {
		log.Fatal(err)
	}
	defer os.Remove(tmpl.Name())
	if _, err := io.WriteString(tmpl, functionTemplate(w)); err != nil {
		log.Fatal(err)
	}
	if err := tmpl.Close(); err != nil {
		log.Fatal(err)
	}

	return runAddchain("gen", "-tmpl", tmpl.Name(), acc)
}

func search(expr string) string {
	acc, err := os.CreateTemp(".", "secp256k1-addchain-*.acc")
	if err != nil {
		log.Fatal(err)
	}
	defer acc.Close()
	log.Printf("searching addition chain for %s", expr)
	out := runAddchain("search", expr)
	if _, err := acc.WriteString(out); err != nil {
		log.Fatal(err)
	}
	return acc.Name()
}

func runAddchain(args ...string) string {
	cmd := addchainCommand(args...)
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		log.Fatalf("addchain %s: %v\n%s", strings.Join(args, " "), err, stderr.String())
	}
	if stderr.Len() > 0 {
		log.Print(stderr.String())
	}
	return string(out)
}

func addchainCommand(args ...string) *exec.Cmd {
	if bin := os.Getenv("ADDCHAIN_BIN"); bin != "" {
		return exec.Command(bin, args...)
	}
	image := os.Getenv("FIAT_CRYPTO_GO_TOOL_IMAGE")
	if image == "" {
		image = defaultToolImage
	}
	cwd, err := os.Getwd()
	if err != nil {
		log.Fatal(err)
	}
	all := []string{
		"run",
		"--rm",
		"--entrypoint", "addchain",
		"-v", fmt.Sprintf("%s:/work", cwd),
		"-w", "/work",
		image,
	}
	all = append(all, args...)
	return exec.Command("docker", all...)
}

func functionTemplate(w wrapper) string {
	return strings.NewReplacer(
		"COMMENT", w.Comment,
		"NAME", w.Name,
		"HELPER", w.Helper,
	).Replace(`// COMMENT
func (z *Element) NAME(x *Element) *Element {
	out := HELPER(*x)
	return z.Set(&out)
}

func HELPER(x Element) Element {
	// Addition chain:
	//
	{{- range lines (format .Script) }}
	//	{{ . }}
	{{- end }}
	var z Element
	var (
		{{- range .Program.Temporaries }}
		{{ . }} Element
		{{- end }}
	)

	{{ range $i := .Program.Instructions }}
	{{- with add $i.Op }}
	{{ $i.Output }}.Mul(&{{ .X }}, &{{ .Y }})
	{{ end -}}

	{{- with double $i.Op }}
	{{ $i.Output }}.Square(&{{ .X }})
	{{ end -}}

	{{- with shift $i.Op -}}
	{{ $i.Output }}.SquareN(&{{ .X }}, {{ .S }})
	{{ end -}}
	{{- end }}
	return z
}
`)
}
