name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: ["^1.26", "^1.25"]
    steps:
      - uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.golang }}"
          check-latest: true

      - run: go build ./...
      - run: gofmt -d .
      - run: go vet ./...
      - run: go mod tidy -diff
      - run: go fix -diff ./...
      - name: run unit test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.txt
