name: test
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        golang: ["stable", "oldstable"]
    steps:
      - uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "${{ matrix.golang }}"
          check-latest: true

      - run: go build ./...
      - run: gofmt -d .
      - run: go vet ./...
      - run: go mod tidy -diff
      - name: run unit test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload Coverage report to CodeCov
        uses: codecov/codecov-action@v7
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: ./coverage.txt

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup go
        uses: actions/setup-go@v6
        with:
          go-version: "stable"
          check-latest: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - run: go generate ./internal/secp256k1

      - run: git diff --exit-code
